/* Connects the order flow to the secure server function when it is configured. */
(() => {
  const ra = (selector) => document.querySelector(selector);
  const escapeLive = (value) => String(value || '').replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[char]));
  let liveStatus = 'checking';

  async function refreshLiveStatus() {
    try {
      const response = await fetch('/api/run-agent', { headers: { accept: 'application/json' } });
      if (!response.ok) throw new Error('not ready');
      const status = await response.json();
      liveStatus = status.ready && status.execution === 'private-demo-enabled' ? 'ready' : 'setup';
    } catch { liveStatus = 'backend'; }
  }

  function showLiveBanner() {
    const sheet = ra('#hire-modal .sheet');
    if (!sheet || ra('#live-agent-banner')) return;
    const message = liveStatus === 'ready' ? 'This agent will create a real AI delivery after you place the order.' : 'Live execution is not connected yet. This order will show the exact setup step instead of pretending to complete work.';
    ra('#checkout-assurance')?.insertAdjacentHTML('beforebegin', `<aside class="live-agent-banner" id="live-agent-banner"><b>✓</b><div><strong>${liveStatus === 'ready' ? 'Live agent ready' : 'Honest demo mode'}</strong>${message}</div></aside>`);
  }

  function renderLiveOrders() {
    const prior = renderOrders;
    renderOrders = () => {
      prior();
      buyerOrders.forEach((order, index) => {
        if (!order.liveExecution) return;
        const card = document.querySelectorAll('.order-card')[index];
        if (!card || card.querySelector('[data-live-output]')) return;
        if (order.delivery) card.insertAdjacentHTML('beforeend', `<button class="live-order-button" data-live-output="${order.id}">View live delivery <span>AI result</span></button>`);
        if (order.executionError) card.insertAdjacentHTML('beforeend', `<div class="live-setup"><strong>Live execution needs setup</strong>${escapeLive(order.executionError)}<br><b>Open Profile → Team workspace after deployment.</b></div>`);
      });
    };
  }

  async function runOrder() {
    const brief = ra('#task-brief')?.value.trim() || '';
    if (!activeAgent || brief.length < 12) return;
    const tier = activeAgent.tiers[selectedTier];
    const order = { id: Date.now(), agentId: activeAgent.id, title: activeAgent.listingTitle, brief, tier, status: 'In progress', liveExecution: true, startedAt: Date.now() };
    buyerOrders.unshift(order);
    save();
    closeModals();
    showScreen('orders-screen');
    toast(`${activeAgent.name} is starting your task.`);
    try {
      const response = await fetch('/api/run-agent', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ agentId: activeAgent.id, brief, tier: tier.name }) });
      const result = await response.json();
      if (!response.ok) throw new Error(result.error || 'The live agent could not complete this task.');
      order.status = 'Delivered';
      order.delivery = result.delivery;
      order.liveModel = result.model;
      toast(`${activeAgent.name} delivered your work for review.`);
    } catch (error) {
      order.status = 'Setup required';
      order.executionError = error.message || 'Live execution could not start.';
      toast('This order needs live-agent setup before it can run.');
    }
    save();
    renderOrders();
    if (typeof renderBuyerOrders === 'function') renderBuyerOrders();
  }

  document.addEventListener('click', event => {
    const button = event.target.closest('button');
    if (!button) return;
    if (button.id === 'hire-button' || button.id === 'agent-page-buy' || button.dataset.tier) queueMicrotask(showLiveBanner);
    if (button.dataset.liveOutput) {
      const order = buyerOrders.find(item => item.id === +button.dataset.liveOutput);
      if (!order?.delivery) return;
      ra('#daily-output-label').textContent = `${agentFor(order.agentId).name.toUpperCase()} LIVE DELIVERY`;
      ra('#daily-output').innerHTML = `<p class="live-delivery-note">Generated by the configured server-side agent. Review before accepting.</p><div class="live-delivery">${escapeLive(order.delivery)}</div>`;
      openModal('daily-output-modal');
    }
  });

  document.addEventListener('click', event => {
    const button = event.target.closest('button');
    if (!button || button.id !== 'confirm-hire') return;
    const brief = ra('#task-brief')?.value.trim() || '';
    if (brief.length < 12) return;
    event.preventDefault();
    event.stopImmediatePropagation();
    runOrder();
  }, true);

  const originalOpenHire = openHire;
  openHire = () => { originalOpenHire(); showLiveBanner(); };
  refreshLiveStatus();
  renderLiveOrders();
})();
